name: Tests

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      scheme:
        required: true
        type: string
      destination:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test NextcloudKit
      run: |
        xcodebuild test -project ${{ inputs.project }} -scheme "${{ inputs.scheme }}" -destination "${{ inputs.destination }}"
    
