name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches:
      - master
      - develop

env:
  DESTINATION: platform=iOS Simulator,name=iPhone 14
  SCHEME: NextcloudKit

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macOS-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Set env var
      run: echo "DEVELOPER_DIR=$(xcode-select --print-path)" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Build NextcloudKit
      run: |
        xcodebuild build test -scheme "$SCHEME" -destination "$DESTINATION" -enableCodeCoverage YES
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # v3.1.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unit
        fail_ci_if_error: true

    
